### ISSUE TITLE
I'm having trouble getting this code to work.

### ISSUE THREAD

**Issue by mmelatti** [merterhk/JustifiedTextView#2]
where do you place the

JustifiedTextView jtv= new JustifiedTextView(getApplicationContext(), "Lorem ipsum dolor sit amet... ");
LinearLayout place = (LinearLayout) findViewById(R.id.book_profile_content);
place.addView(jtv);

portion of code in your main.java file?

also what should replace the "book_profile_content" portion of code?

Thanks for the help!

**Comment by merterhk** [comment]
book_profile_content was any element to put inside a container like ScrollView or Layout.
